name: Update

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

defaults:
  run:
    shell: bash
    working-directory: scripts

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: ".bun-version"

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          working-directory: "scripts"

      - name: Update
        run: |
          bun i
          rake
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Commit changes
        working-directory: ${{ github.workspace }}
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "actions@github.com"

          git add .
          git commit -m "feat: 内容を更新" || echo "No changes to commit"
          git push origin main || echo "No changes to push"
